package app.saving.controller.dto;

import app.saving.entity.CashFlowEntity;
import app.saving.entity.TransactionEntity;

import java.time.LocalDate;

public record TransactionDto(
        Long id,
        Long idAccount,
        LocalDate date,
        String originalWording,
        Double value,
        String formattedValue
) {
    // Record constructor is automatically generated by the compiler
    // You don't need to explicitly declare fields, getters, setters, or constructors.

    public static TransactionDto create(TransactionEntity transactionEntity) {
        return new TransactionDto(transactionEntity.getId(),
                transactionEntity.getAccountId(),
                transactionEntity.getDate(),
                transactionEntity.getOriginalWording(),
                transactionEntity.getValue(),
                transactionEntity.getFormattedValue());
    }
}



